.TH "C:/Users/cbanw/GitHub/Spectrum Health Systems/Outpost31/src/Core Directory Reference" 3 "Mon Jul 1 2024" "Outpost31" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/cbanw/GitHub/Spectrum Health Systems/Outpost31/src/Core Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBAvatar\fP"
.br
.ti -1c
.RI "directory \fBConfiguration\fP"
.br
.ti -1c
.RI "directory \fBFramework\fP"
.br
.ti -1c
.RI "directory \fBLogger\fP"
.br
.ti -1c
.RI "directory \fBNtstWebService\fP"
.br
.ti -1c
.RI "directory \fBSession\fP"
.br
.ti -1c
.RI "directory \fBUtilities\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBParseScriptParameter\&.cs\fP"
.br
.ti -1c
.RI "file \fBTingenApp\&.cs\fP"
.br
.in -1c
