.TH "C:/Users/cbanw/GitHub/Spectrum Health Systems/Outpost31/src Directory Reference" 3 "Mon Jul 1 2024" "Outpost31" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/cbanw/GitHub/Spectrum Health Systems/Outpost31/src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBCore\fP"
.br
.ti -1c
.RI "directory \fBModule\fP"
.br
.ti -1c
.RI "directory \fBobj\fP"
.br
.ti -1c
.RI "directory \fBProperties\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBWelcomeToOutpost31\&.cs\fP"
.br
.in -1c
