.TH "C:/Users/cbanw/GitHub/Spectrum Health Systems/Outpost31/src/Core/Utilities Directory Reference" 3 "Mon Jul 1 2024" "Outpost31" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/cbanw/GitHub/Spectrum Health Systems/Outpost31/src/Core/Utilities Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBDuFile\&.cs\fP"
.br
.ti -1c
.RI "file \fBDuJson\&.cs\fP"
.br
.in -1c
