.TH "C:/Users/cbanw/GitHub/Spectrum Health Systems/Outpost31/src/Core/Framework Directory Reference" 3 "Mon Jul 1 2024" "Outpost31" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/cbanw/GitHub/Spectrum Health Systems/Outpost31/src/Core/Framework Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBCatalog\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBMaintenance\&.cs\fP"
.br
.ti -1c
.RI "file \fBPaths\&.cs\fP"
.br
.ti -1c
.RI "file \fBRefresh\&.cs\fP"
.br
.in -1c
