.TH "md__c_1_2_users_2cbanw_2_git_hub_2_spectrum_01_health_01_systems_2_outpost31_2src_2_r_e_a_d_m_e" 3 "Mon Jul 1 2024" "Outpost31" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__c_1_2_users_2cbanw_2_git_hub_2_spectrum_01_health_01_systems_2_outpost31_2src_2_r_e_a_d_m_e \- README 
.PP

.PP
 
.PP
.PP
\fBThis is a work in progress, and will be complete by the release of Tingen 24\&.6\fP
.SH "About Outpost31"
.PP
The \fBOutpost31\fP project contains the core components and modules for the \fRTingen\fP web service\&.
.SH "Repository branches"
.PP
.IP "\(bu" 2
\fRmain\fP The stable branch of \fBOutpost31\fP
.IP "\(bu" 2
\fRdevelopment\fP The current development branch of \fBOutpost31\fP 
.PP

