.TH "Outpost31.Module.OpenIncident.Verify" 3 "Mon Jul 1 2024" "Outpost31" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Outpost31.Module.OpenIncident.Verify \- VerifyAuthor command\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBOriginalAuthorIsOpening\fP (\fBTingenSession\fP tnSession)"
.br
.ti -1c
.RI "static void \fBOriginalAuthorIsSubmitting\fP (\fBTingenSession\fP tnSession)"
.br
.RI "\fBVerify\fP the Avatar user is the same as the original author\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static string \fBAssemblyName\fP = Assembly\&.GetExecutingAssembly()\&.GetName()\&.Name\fR [get, set]\fP"
.br
.RI "Assembly name for log files\&. "
.in -1c
.SH "Detailed Description"
.PP 
VerifyAuthor command\&. 
.SH "Member Function Documentation"
.PP 
.SS "static void Outpost31\&.Module\&.OpenIncident\&.Verify\&.OriginalAuthorIsOpening (\fBTingenSession\fP tnSession)\fR [static]\fP"

.SS "static void Outpost31\&.Module\&.OpenIncident\&.Verify\&.OriginalAuthorIsSubmitting (\fBTingenSession\fP tnSession)\fR [static]\fP"

.PP
\fBVerify\fP the Avatar user is the same as the original author\&. 
.PP
\fBParameters\fP
.RS 4
\fItnSession\fP 
.RE
.PP

.SH "Property Documentation"
.PP 
.SS "string Outpost31\&.Module\&.OpenIncident\&.Verify\&.AssemblyName = Assembly\&.GetExecutingAssembly()\&.GetName()\&.Name\fR [static]\fP, \fR [get]\fP, \fR [set]\fP"

.PP
Assembly name for log files\&. 
.IP "\(bu" 2
Define the assembly name here so it can be used to write log files throughout the class\&. 
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Outpost31 from the source code\&.
