.TH "Outpost31.Module.OpenIncident.ModuleOpenIncident" 3 "Mon Jul 1 2024" "Outpost31" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Outpost31.Module.OpenIncident.ModuleOpenIncident
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBModuleOpenIncident\fP \fBBuildDefaultModOpenIncident\fP (\fBTraceLog\fP traceInfo)"
.br
.ti -1c
.RI "static \fBModuleOpenIncident\fP \fBLoad\fP (string modConfigFilePath, string currentSessionPath, OptionObject2015 workOptionObject, \fBTraceLog\fP traceInfo)"
.br
.ti -1c
.RI "static string \fBGetFullName\fP (string filePath, string avatarName, \fBTraceLog\fP traceInfo)"
.br
.ti -1c
.RI "static void \fBGetAuthorInformation\fP (\fBTingenSession\fP tnSession)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static string \fBAssemblyName\fP = Assembly\&.GetExecutingAssembly()\&.GetName()\&.Name\fR [get, set]\fP"
.br
.RI "Assembly name for log files\&. "
.ti -1c
.RI "List< string > \fBWhitelist\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "List< string > \fBBlacklist\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBOriginalFullName\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBCurrentFullName\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBPersonCompletingIncidentFormFieldId\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBFormOpenMessage\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBFormOpenErrorCode\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBFormSubmitMessage\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBFormSubmitErrorCode\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static \fBModuleOpenIncident\fP Outpost31\&.Module\&.OpenIncident\&.ModuleOpenIncident\&.BuildDefaultModOpenIncident (\fBTraceLog\fP traceInfo)\fR [static]\fP"

.SS "static void Outpost31\&.Module\&.OpenIncident\&.ModuleOpenIncident\&.GetAuthorInformation (\fBTingenSession\fP tnSession)\fR [static]\fP"

.SS "static string Outpost31\&.Module\&.OpenIncident\&.ModuleOpenIncident\&.GetFullName (string filePath, string avatarName, \fBTraceLog\fP traceInfo)\fR [static]\fP"

.SS "static \fBModuleOpenIncident\fP Outpost31\&.Module\&.OpenIncident\&.ModuleOpenIncident\&.Load (string modConfigFilePath, string currentSessionPath, OptionObject2015 workOptionObject, \fBTraceLog\fP traceInfo)\fR [static]\fP"

.SH "Property Documentation"
.PP 
.SS "string Outpost31\&.Module\&.OpenIncident\&.ModuleOpenIncident\&.AssemblyName = Assembly\&.GetExecutingAssembly()\&.GetName()\&.Name\fR [static]\fP, \fR [get]\fP, \fR [set]\fP"

.PP
Assembly name for log files\&. 
.IP "\(bu" 2
Define the assembly name here so it can be used to write log files throughout the class\&. 
.PP

.SS "List<string> Outpost31\&.Module\&.OpenIncident\&.ModuleOpenIncident\&.Blacklist\fR [get]\fP, \fR [set]\fP"

.SS "string Outpost31\&.Module\&.OpenIncident\&.ModuleOpenIncident\&.CurrentFullName\fR [get]\fP, \fR [set]\fP"

.SS "string Outpost31\&.Module\&.OpenIncident\&.ModuleOpenIncident\&.FormOpenErrorCode\fR [get]\fP, \fR [set]\fP"

.SS "string Outpost31\&.Module\&.OpenIncident\&.ModuleOpenIncident\&.FormOpenMessage\fR [get]\fP, \fR [set]\fP"

.SS "string Outpost31\&.Module\&.OpenIncident\&.ModuleOpenIncident\&.FormSubmitErrorCode\fR [get]\fP, \fR [set]\fP"

.SS "string Outpost31\&.Module\&.OpenIncident\&.ModuleOpenIncident\&.FormSubmitMessage\fR [get]\fP, \fR [set]\fP"

.SS "string Outpost31\&.Module\&.OpenIncident\&.ModuleOpenIncident\&.OriginalFullName\fR [get]\fP, \fR [set]\fP"

.SS "int Outpost31\&.Module\&.OpenIncident\&.ModuleOpenIncident\&.PersonCompletingIncidentFormFieldId\fR [get]\fP, \fR [set]\fP"

.SS "List<string> Outpost31\&.Module\&.OpenIncident\&.ModuleOpenIncident\&.Whitelist\fR [get]\fP, \fR [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Outpost31 from the source code\&.
