.TH "Outpost31.Core.Framework.Catalog.TingenPaths" 3 "Thu Jun 27 2024" "Outpost31" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Outpost31.Core.Framework.Catalog.TingenPaths \- Specific to Tingen\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBTingenPaths\fP \fBBuildObject\fP (string tnDataRoot)"
.br
.RI "Builds the Tingen path object\&. "
.ti -1c
.RI "static List< string > \fBRequiredPaths\fP (\fBTingenPaths\fP tnPaths)"
.br
.RI "Returns a list of required Tingen paths\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBRoot\fP\fR [get, set]\fP"
.br
.RI "Root path for Tingen data\&. "
.ti -1c
.RI "string \fBPrimeval\fP\fR [get, set]\fP"
.br
.RI "Path for Tingen Primeval data\&. "
.in -1c
.SH "Detailed Description"
.PP 
Specific to Tingen\&. 
.SH "Member Function Documentation"
.PP 
.SS "static \fBTingenPaths\fP Outpost31\&.Core\&.Framework\&.Catalog\&.TingenPaths\&.BuildObject (string tnDataRoot)\fR [static]\fP"

.PP
Builds the Tingen path object\&. 
.PP
\fBParameters\fP
.RS 4
\fItnDataRoot\fP The Tingen data root\&.
.RE
.PP
\fBReturns\fP
.RS 4
A collection of Tingen paths\&.
.RE
.PP

.SS "static List< string > Outpost31\&.Core\&.Framework\&.Catalog\&.TingenPaths\&.RequiredPaths (\fBTingenPaths\fP tnPaths)\fR [static]\fP"

.PP
Returns a list of required Tingen paths\&. 
.PP
\fBParameters\fP
.RS 4
\fItnPaths\fP The Tingen paths\&.
.RE
.PP
\fBReturns\fP
.RS 4
The list of required Tingen paths\&.
.RE
.PP

.SH "Property Documentation"
.PP 
.SS "string Outpost31\&.Core\&.Framework\&.Catalog\&.TingenPaths\&.Primeval\fR [get]\fP, \fR [set]\fP"

.PP
Path for Tingen Primeval data\&. C:\\TingenData\\Primeval
.SS "string Outpost31\&.Core\&.Framework\&.Catalog\&.TingenPaths\&.Root\fR [get]\fP, \fR [set]\fP"

.PP
Root path for Tingen data\&. C:\\TingenData

.SH "Author"
.PP 
Generated automatically by Doxygen for Outpost31 from the source code\&.
