.TH "Outpost31.Core.NtstWebService.NtstWebServiceSecurity" 3 "Thu Jun 27 2024" "Outpost31" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Outpost31.Core.NtstWebService.NtstWebServiceSecurity
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBNtstWebServiceSecurity\fP \fBBuildDefaultSecurityObject\fP ()"
.br
.ti -1c
.RI "static \fBNtstWebServiceSecurity\fP \fBLoad\fP (string ntstWebServiceSecurityPath, string ntstWebServiceSecurityFileName)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBWebServiceUser\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBWebServicePassword\fP\fR [get, set]\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Outpost31 from the source code\&.
