.TH "Outpost31.Core.Logger.TraceLog" 3 "Thu Jun 27 2024" "Outpost31" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Outpost31.Core.Logger.TraceLog \- Soon\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBTraceLog\fP \fBBuildInfo\fP (string traceLogPath, int traceLogLevel, int traceLogDelay)"
.br
.RI "Build the trace log information\&. "
.ti -1c
.RI "static void \fBCreate\fP (int logLevel, string assemblyName, \fBTraceLog\fP traceInfo, string fromClass, string fromMethod, int line)"
.br
.RI "Soon\&. "
.ti -1c
.RI "static void \fBCreate\fP (int logLevel, string assemblyName, \fBTraceLog\fP traceInfo, string fromClass, string fromMethod, int line, string message)"
.br
.RI "Soon\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBTraceLogPath\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBTraceLogLevel\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBTraceLogDelay\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Soon\&. 
.SH "Member Function Documentation"
.PP 
.SS "static \fBTraceLog\fP Outpost31\&.Core\&.Logger\&.TraceLog\&.BuildInfo (string traceLogPath, int traceLogLevel, int traceLogDelay)\fR [static]\fP"

.PP
Build the trace log information\&. The \fBTraceLogPath\fP is the same as the \fBtnSession\&.Framework\&.SystemCodePath\&.Session\fP It's here so we can easily pass all the data 
.PP
\fBParameters\fP
.RS 4
\fItraceLogLevel\fP 
.br
\fItraceLogDelay\fP 
.br
\fItraceLogPath\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.SS "static void Outpost31\&.Core\&.Logger\&.TraceLog\&.Create (int logLevel, string assemblyName, \fBTraceLog\fP traceInfo, string fromClass, string fromMethod, int line)\fR [static]\fP"

.PP
Soon\&. 
.PP
\fBParameters\fP
.RS 4
\fItraceLevel\fP 
.br
\fItraceInfo\fP 
.br
\fIassemblyName\fP 
.br
\fIcallPath\fP 
.br
\fIcallMember\fP 
.br
\fIcallLine\fP 
.RE
.PP

.SS "static void Outpost31\&.Core\&.Logger\&.TraceLog\&.Create (int logLevel, string assemblyName, \fBTraceLog\fP traceInfo, string fromClass, string fromMethod, int line, string message)\fR [static]\fP"

.PP
Soon\&. 
.PP
\fBParameters\fP
.RS 4
\fIlogLevel\fP 
.br
\fIassemblyName\fP 
.br
\fItraceInfo\fP 
.br
\fIfromClass\fP 
.br
\fIfromMethod\fP 
.br
\fIline\fP 
.br
\fImessage\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Outpost31 from the source code\&.
