.TH "Outpost31.Core.NtstWebService.NtstWebServiceSecurity" 3 "Mon Jul 1 2024" "Outpost31" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Outpost31.Core.NtstWebService.NtstWebServiceSecurity
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBNtstWebServiceSecurity\fP \fBBuildDefaultSecurityObject\fP ()"
.br
.ti -1c
.RI "static \fBNtstWebServiceSecurity\fP \fBLoad\fP (string ntstWebServiceSecurityPath, string ntstWebServiceSecurityFileName)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBWebServiceUser\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBWebServicePassword\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static \fBNtstWebServiceSecurity\fP Outpost31\&.Core\&.NtstWebService\&.NtstWebServiceSecurity\&.BuildDefaultSecurityObject ()\fR [static]\fP"

.SS "static \fBNtstWebServiceSecurity\fP Outpost31\&.Core\&.NtstWebService\&.NtstWebServiceSecurity\&.Load (string ntstWebServiceSecurityPath, string ntstWebServiceSecurityFileName)\fR [static]\fP"

.SH "Property Documentation"
.PP 
.SS "string Outpost31\&.Core\&.NtstWebService\&.NtstWebServiceSecurity\&.WebServicePassword\fR [get]\fP, \fR [set]\fP"

.SS "string Outpost31\&.Core\&.NtstWebService\&.NtstWebServiceSecurity\&.WebServiceUser\fR [get]\fP, \fR [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Outpost31 from the source code\&.
