.TH "Outpost31.Core.Logger.PrimevalLog" 3 "Mon Jul 1 2024" "Outpost31" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Outpost31.Core.Logger.PrimevalLog \- Primeval logs\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBCreate\fP (string assemblyName, string message, string fromClass, string fromMethod, int line)"
.br
.RI "Creates a Primeval log\&. "
.ti -1c
.RI "static void \fBDevelopmentCleanup\fP ()"
.br
.RI "Removes old Primeval logs\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static string \fBPrimevalLogPath\fP = @'C:\\TingenData\\Primeval'\fR [get, set]\fP"
.br
.RI "Primeval log path\&. "
.in -1c
.SH "Detailed Description"
.PP 
Primeval logs\&. 
.SH "Member Function Documentation"
.PP 
.SS "static void Outpost31\&.Core\&.Logger\&.PrimevalLog\&.Create (string assemblyName, string message, string fromClass, string fromMethod, int line)\fR [static]\fP"

.PP
Creates a Primeval log\&. 
.PP
\fBParameters\fP
.RS 4
\fIassemblyName\fP 
.br
\fImessage\fP 
.br
\fIfromClass\fP 
.br
\fIfromMethod\fP 
.br
\fIline\fP 
.RE
.PP
.PP
.IP "\(bu" 2
Before a Primeval log is written, the Primeval log path is verified to ensure it exists\&.
.br

.IP "\(bu" 2
Log files may be created quickly - and possibly at the same time - so a pause is added to ensure logs are unique\&. 
.PP
.PP
To create a simple Primeval log: 
.PP
.nf
LogEvent\&.Primeval(AssemblyName);
LogEvent\&.Primeval(Assembly\&.GetExecutingAssembly()\&.GetName()\&.Name);

.fi
.PP
 To create a Primeval log with custom content: 
.PP
.nf
LogEvent\&.Primeval(AssemblyName, message);
LogEvent\&.Primeval(Assembly\&.GetExecutingAssembly()\&.GetName()\&.Name, message);

.fi
.PP
 
.SS "static void Outpost31\&.Core\&.Logger\&.PrimevalLog\&.DevelopmentCleanup ()\fR [static]\fP"

.PP
Removes old Primeval logs\&. 
.IP "\(bu" 2
Not currently used\&. 
.PP

.SH "Property Documentation"
.PP 
.SS "string Outpost31\&.Core\&.Logger\&.PrimevalLog\&.PrimevalLogPath = @'C:\\TingenData\\Primeval'\fR [static]\fP, \fR [get]\fP, \fR [set]\fP"

.PP
Primeval log path\&. 
.IP "\(bu" 2
Primeval logs are written to \fIC:\\TingenData\\Primeval</i>, defined here so it can be easily changed if needed\&. \fP
.PP
.PP
\fI \fP
.PP
\fI \fP

.SH "Author"
.PP 
Generated automatically by Doxygen for Outpost31 from the source code\&.
