.TH "Outpost31.Core.Framework.Maintenance" 3 "Mon Jul 1 2024" "Outpost31" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Outpost31.Core.Framework.Maintenance \- Methods for maintaining the Tingen framework\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBCleanSessionData\fP ()"
.br
.RI "Soon\&. "
.ti -1c
.RI "static void \fBVerifyFramework\fP (\fBTingenSession\fP tnSession)"
.br
.RI "Verify the Tingen framework\&. "
.ti -1c
.RI "static void \fBRefreshDirectory\fP (string directoryPath)"
.br
.RI "Delete a directory, then recreate it\&. "
.ti -1c
.RI "static void \fBVerifyDirectory\fP (string directoryPath)"
.br
.RI "Verify a directory exists, and create it if it does not\&. "
.ti -1c
.RI "static void \fBVerifyDirectories\fP (List< string > directoryPaths)"
.br
.RI "Verify a list of directories exist, and create them if they do not\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static string \fBAssemblyName\fP = Assembly\&.GetExecutingAssembly()\&.GetName()\&.Name\fR [get, set]\fP"
.br
.RI "Assembly name for log files\&. "
.in -1c
.SS "Static Private Member Functions"

.in +1c
.ti -1c
.RI "static void \fBTESTER\fP ()"
.br
.RI "Tester\&. "
.in -1c
.SH "Detailed Description"
.PP 
Methods for maintaining the Tingen framework\&. 
.SH "Member Function Documentation"
.PP 
.SS "static void Outpost31\&.Core\&.Framework\&.Maintenance\&.CleanSessionData ()\fR [static]\fP"

.PP
Soon\&. 
.SS "static void Outpost31\&.Core\&.Framework\&.Maintenance\&.RefreshDirectory (string directoryPath)\fR [static]\fP"

.PP
Delete a directory, then recreate it\&. 
.PP
\fBParameters\fP
.RS 4
\fIdirectoryPath\fP The path to the directory to refresh\&.
.RE
.PP

.SS "static void Outpost31\&.Core\&.Framework\&.Maintenance\&.TESTER ()\fR [static]\fP, \fR [private]\fP"

.PP
Tester\&. 
.SS "static void Outpost31\&.Core\&.Framework\&.Maintenance\&.VerifyDirectories (List< string > directoryPaths)\fR [static]\fP"

.PP
Verify a list of directories exist, and create them if they do not\&. 
.PP
\fBParameters\fP
.RS 4
\fIdirectoryPaths\fP The list of directories to verify\&.
.RE
.PP

.SS "static void Outpost31\&.Core\&.Framework\&.Maintenance\&.VerifyDirectory (string directoryPath)\fR [static]\fP"

.PP
Verify a directory exists, and create it if it does not\&. 
.PP
\fBParameters\fP
.RS 4
\fIdirectoryPath\fP The path to the directory to verify\&.
.RE
.PP

.SS "static void Outpost31\&.Core\&.Framework\&.Maintenance\&.VerifyFramework (\fBTingenSession\fP tnSession)\fR [static]\fP"

.PP
Verify the Tingen framework\&. 
.PP
\fBParameters\fP
.RS 4
\fItnSession\fP The Tingen \fBSession\fP object\&.
.RE
.PP

.SH "Property Documentation"
.PP 
.SS "string Outpost31\&.Core\&.Framework\&.Maintenance\&.AssemblyName = Assembly\&.GetExecutingAssembly()\&.GetName()\&.Name\fR [static]\fP, \fR [get]\fP, \fR [set]\fP"

.PP
Assembly name for log files\&. 
.IP "\(bu" 2
Define the assembly name here so it can be used to write log files throughout the class\&. 
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Outpost31 from the source code\&.
