.TH "Outpost31.Core.Avatar.AvatarData" 3 "Thu Jun 27 2024" "Outpost31" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Outpost31.Core.Avatar.AvatarData \- Avatar-specific data and logic\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBAvatarData\fP \fBBuildObject\fP (OptionObject2015 sentOptionObject, string sentScriptParameter)"
.br
.RI "Builds a new \fB\fBAvatarData\fP\fP object\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBAvatarSystemCode\fP\fR [get, set]\fP"
.br
.RI "The \fB\fBAvatar\fP System Code\fP that Tingen will be using\&. "
.ti -1c
.RI "string \fBSentScriptParameter\fP\fR [get, set]\fP"
.br
.RI "The \fBScript Parameter\fP sent from \fBAvatar\fP\&. "
.ti -1c
.RI "OptionObject2015 \fBSentOptionObject\fP\fR [get, set]\fP"
.br
.RI "The original \fBOptionObject\fP sent from \fBAvatar\fP\&. "
.ti -1c
.RI "OptionObject2015 \fBWorkOptionObject\fP\fR [get, set]\fP"
.br
.RI "The \fBOptionObject\fP that may be modified during the session\&. "
.ti -1c
.RI "OptionObject2015 \fBReturnOptionObject\fP\fR [get, set]\fP"
.br
.RI "The \fBOptionObject\fP that will be returned to \fBAvatar\fP\&. "
.in -1c
.SH "Detailed Description"
.PP 
Avatar-specific data and logic\&. 

This class should only contain the following Avatar-specific data:
.br
 
.PD 0
.IP "\(bu" 2
The \fIAvatarSystemCode\fP  
.IP "\(bu" 2
The \fISentScriptParameter\fP  
.IP "\(bu" 2
The \fISentOptionObject\fP  
.IP "\(bu" 2
The \fIWorkOptionObject\fP  
.IP "\(bu" 2
The \fIReturnOptionObject\fP  
.PP
.PP
.IP "\(bu" 2
This object is added to the Tingen \fBSession\fP object when Tingen starts\&.
.br
 
.PP

.SH "Member Function Documentation"
.PP 
.SS "static \fBAvatarData\fP Outpost31\&.Core\&.Avatar\&.AvatarData\&.BuildObject (OptionObject2015 sentOptionObject, string sentScriptParameter)\fR [static]\fP"

.PP
Builds a new \fB\fBAvatarData\fP\fP object\&. 
.PP
\fBParameters\fP
.RS 4
\fIsentOptionObject\fP The OptionObject sent from \fBAvatar\fP\&.
.br
\fIsentScriptParameter\fP The ScriptParameter sent from \fBAvatar\fP\&.
.RE
.PP
.PP
.IP "\(bu" 2
The \fIsentScriptParameter\fP  is converted to lowercase so it is easier to compare against\&.
.br

.IP "\(bu" 2
The \fIworkOptionObject\fP  is cloned from the \fIsentOptionObject\fP  so it can be modified without affecting the original data\&.
.br

.IP "\(bu" 2
The \fIreturnOptionObject\fP  is initally set to 'null', and will be formatted/finalized prior to returning to \fBAvatar\fP\&.
.br

.IP "\(bu" 2
More information about OptionObjects here
.PP
.PP
\&. 
.br
 
.PP
\fBReturns\fP
.RS 4
The necessary \fBAvatar\fP data\&.
.RE
.PP

.SH "Property Documentation"
.PP 
.SS "string Outpost31\&.Core\&.Avatar\&.AvatarData\&.AvatarSystemCode\fR [get]\fP, \fR [set]\fP"

.PP
The \fB\fBAvatar\fP System Code\fP that Tingen will be using\&. Valid \fBAvatar\fP System Codes: UAT Used for the \fIdevelopment\fP version of Tingen\&.  LIVE Used for the \fIproduction\fP version of Tingen\&.  
.IP "\(bu" 2
More information about \fBAvatar\fP System Codes here
.PP
.PP
\&. 
.SS "OptionObject2015 Outpost31\&.Core\&.Avatar\&.AvatarData\&.ReturnOptionObject\fR [get]\fP, \fR [set]\fP"

.PP
The \fBOptionObject\fP that will be returned to \fBAvatar\fP\&. 
.IP "\(bu" 2
The \fIReturnOptionObject\fP  must be formatted properly to be returned to \fBAvatar\fP\&.
.br

.IP "\(bu" 2
More information about OptionObjects here
.PP
.PP
\&. 
.br
 
.SS "OptionObject2015 Outpost31\&.Core\&.Avatar\&.AvatarData\&.SentOptionObject\fR [get]\fP, \fR [set]\fP"

.PP
The original \fBOptionObject\fP sent from \fBAvatar\fP\&. 
.IP "\(bu" 2
\fIThe \fISentOptionObject\fP  should not be modified\fP\&.
.br

.IP "\(bu" 2
All work should be done with the \fIWorkOptionObject\fP \&.
.br

.IP "\(bu" 2
More information about OptionObjects here
.PP
.PP
\&. 
.SS "string Outpost31\&.Core\&.Avatar\&.AvatarData\&.SentScriptParameter\fR [get]\fP, \fR [set]\fP"

.PP
The \fBScript Parameter\fP sent from \fBAvatar\fP\&. The Script Parameter is a '-' delimited string with the following compoents: \fBModule\fP The Tingen \fI\fBModule\fP\fP that will be doing the session work (ex: 'Admin')\&.  Command The Tingen \fICommand\fP request (ex: 'All')\&.  Action The Tingen \fIAction\fP request (ex: 'Status')\&.  Option The optional \fIAction Option\fP (ex: 'Update')\&.  
.IP "\(bu" 2
More information about the \fBAvatar\fP Script Parameter here
.PP
.PP
\&. 
.PP
The following Script Parameter will update all status files: 
.PP
.nf
Admin\-All\-Status\-Update

.fi
.PP
 
.SS "OptionObject2015 Outpost31\&.Core\&.Avatar\&.AvatarData\&.WorkOptionObject\fR [get]\fP, \fR [set]\fP"

.PP
The \fBOptionObject\fP that may be modified during the session\&. 
.IP "\(bu" 2
All work should be done with the \fIWorkOptionObject\fP \&.
.br

.IP "\(bu" 2
When a Tingen session is initialized, the \fIWorkOptionObject\fP  is cloned from the \fISentOptionObject\fP \&.
.br

.IP "\(bu" 2
The \fIWorkOptionObject\fP  \fIis not\fP formatted properly for returning to \fBAvatar\fP\&.
.br

.IP "\(bu" 2
More information about OptionObjects here
.PP
.PP
\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Outpost31 from the source code\&.
