.TH "Outpost31.Core.Logger" 3 "Thu Jun 27 2024" "Outpost31" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Outpost31.Core.Logger
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLogEvent\fP"
.br
.RI "Provides logging functionality\&. "
.ti -1c
.RI "class \fBLoggerCatalog\fP"
.br
.RI "Log catalog for the \fBOutpost31\&.Core\&.Logger\fP namespace\&. "
.ti -1c
.RI "class \fBPrimevalLog\fP"
.br
.RI "Primeval logs\&. "
.ti -1c
.RI "class \fBTraceLog\fP"
.br
.RI "Soon\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Outpost31 from the source code\&.
