.TH "Outpost31.Core.Session.TingenSession" 3 "Mon Jul 1 2024" "Outpost31" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Outpost31.Core.Session.TingenSession \- Contains Tingen session logic\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBTingenSession\fP \fBBuild\fP (OptionObject2015 sentOptionObject, string sentScriptParameter, string tnVersion)"
.br
.RI "Builds the Tingen \fBSession\fP object\&. "
.ti -1c
.RI "static void \fBInitialize\fP (\fBTingenSession\fP tnSession)"
.br
.RI "Soon\&. "
.ti -1c
.RI "static void \fBWriteSessionDetails\fP (\fBTingenSession\fP tnSession)"
.br
.ti -1c
.RI "static Dictionary< string, string > \fBBuildStaticVars\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBTnVersion\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBTnBuild\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBDate\fP\fR [get, set]\fP"
.br
.RI "The session datestamp\&. "
.ti -1c
.RI "string \fBTime\fP\fR [get, set]\fP"
.br
.RI "The session timestamp\&. "
.ti -1c
.RI "bool \fBReturnClonedOptionObject\fP\fR [get, set]\fP"
.br
.RI "Return the cloned OptionObject\&. "
.ti -1c
.RI "\fBConfigSettings\fP \fBTnConfig\fP\fR [get, set]\fP"
.br
.RI "Config\&. "
.ti -1c
.RI "\fBPaths\fP \fBTnPath\fP\fR [get, set]\fP"
.br
.RI "Tingen \fBFramework\fP information\&. "
.ti -1c
.RI "\fBAvatarData\fP \fBAvData\fP\fR [get, set]\fP"
.br
.RI "\fBAvatar\fP components \&. "
.ti -1c
.RI "\fBNtstWebServiceSecurity\fP \fBNtstWebServiceSecurity\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "\fBTraceLog\fP \fBTraceInfo\fP\fR [get, set]\fP"
.br
.RI "Trace log information\&. "
.ti -1c
.RI "\fBModuleOpenIncident\fP \fBModOpenIncident\fP\fR [get, set]\fP"
.br
.RI "\fBModule\fP to open an incident\&. "
.in -1c
.SH "Detailed Description"
.PP 
Contains Tingen session logic\&. 

Properties for the Tingen session are located in \fBTingenSession\&.Properties\&.cs\&.\fP 
.SH "Member Function Documentation"
.PP 
.SS "static \fBTingenSession\fP Outpost31\&.Core\&.Session\&.TingenSession\&.Build (OptionObject2015 sentOptionObject, string sentScriptParameter, string tnVersion)\fR [static]\fP"

.PP
Builds the Tingen \fBSession\fP object\&. 
.PP
\fBParameters\fP
.RS 4
\fIconfigFile\fP The path to the Tingen configuration file\&.
.br
\fIsentOptionObject\fP The OptionObject sent from \fBAvatar\fP\&.
.br
\fIsentScriptParameter\fP The ScriptParameter sent from \fBAvatar\fP\&.
.RE
.PP
.PP
The Tingen \fBSession\fP contains all of the information that Tingen needs to do what it does, including: 
.PD 0
.IP "\(bu" 2
\fBConfiguration\fP settings (user-definable settings from the \fIconfigFile\fP ) 
.IP "\(bu" 2
Static settings (these do not change between sessions) 
.IP "\(bu" 2
Runtime settings (unique to the current session) 
.IP "\(bu" 2
Data sent from \fBAvatar\fP, including the \fIsentOptionObject\fP  and \fIsentScriptParameter\fP  
.IP "\(bu" 2
Data derived from the \fIsentOptionObject\fP  or \fIsentScriptParameter\fP \&. 
.IP "\(bu" 2
Required Tingen \fBModule\fP details\&. 
.PP
.PP
\fBMore information about this method:\fP
.br
 This method is one of the most important in Tingen, as it builds the Tingen \fBSession\fP object\&.
.br

.br
 The \fBSession\fP object is built in this order: 
.PD 0
.IP "1." 4
A basic \fBTingenSession\fP object is initalized with the current date, time, configuration settings, and \fBAvatar\fP data\&. 
.IP "2." 4
\fBFramework\fP information is added seperately\&. 
.IP "3." 4
Trace log information is added seperately\&. 
.IP "4." 4
\fBModule\fP objects are added seperately\&. 
.PP
.PP
\fBReturns\fP
.RS 4
An Tingen \fBSession\fP object\&.
.RE
.PP

.SS "static Dictionary< string, string > Outpost31\&.Core\&.Session\&.TingenSession\&.BuildStaticVars ()\fR [static]\fP"

.SS "static void Outpost31\&.Core\&.Session\&.TingenSession\&.Initialize (\fBTingenSession\fP tnSession)\fR [static]\fP"

.PP
Soon\&. 
.PP
\fBParameters\fP
.RS 4
\fItnSession\fP 
.RE
.PP

.SS "static void Outpost31\&.Core\&.Session\&.TingenSession\&.WriteSessionDetails (\fBTingenSession\fP tnSession)\fR [static]\fP"

.SH "Property Documentation"
.PP 
.SS "\fBAvatarData\fP Outpost31\&.Core\&.Session\&.TingenSession\&.AvData\fR [get]\fP, \fR [set]\fP"

.PP
\fBAvatar\fP components \&. See \fBOutpost31\&.Core\&.Configuration\&.TingenFramework\&.cs\fP for more information\&. 
.SS "string Outpost31\&.Core\&.Session\&.TingenSession\&.Date\fR [get]\fP, \fR [set]\fP"

.PP
The session datestamp\&. 
.SS "\fBModuleOpenIncident\fP Outpost31\&.Core\&.Session\&.TingenSession\&.ModOpenIncident\fR [get]\fP, \fR [set]\fP"

.PP
\fBModule\fP to open an incident\&. 
.SS "\fBNtstWebServiceSecurity\fP Outpost31\&.Core\&.Session\&.TingenSession\&.NtstWebServiceSecurity\fR [get]\fP, \fR [set]\fP"

.SS "bool Outpost31\&.Core\&.Session\&.TingenSession\&.ReturnClonedOptionObject\fR [get]\fP, \fR [set]\fP"

.PP
Return the cloned OptionObject\&. 
.SS "string Outpost31\&.Core\&.Session\&.TingenSession\&.Time\fR [get]\fP, \fR [set]\fP"

.PP
The session timestamp\&. 
.SS "string Outpost31\&.Core\&.Session\&.TingenSession\&.TnBuild\fR [get]\fP, \fR [set]\fP"

.SS "\fBConfigSettings\fP Outpost31\&.Core\&.Session\&.TingenSession\&.TnConfig\fR [get]\fP, \fR [set]\fP"

.PP
Config\&. 
.SS "\fBPaths\fP Outpost31\&.Core\&.Session\&.TingenSession\&.TnPath\fR [get]\fP, \fR [set]\fP"

.PP
Tingen \fBFramework\fP information\&. See \fBOutpost31\&.Core\&.Configuration\&.TingenFramework\&.cs\fP for more information\&. 
.SS "string Outpost31\&.Core\&.Session\&.TingenSession\&.TnVersion\fR [get]\fP, \fR [set]\fP"

.SS "\fBTraceLog\fP Outpost31\&.Core\&.Session\&.TingenSession\&.TraceInfo\fR [get]\fP, \fR [set]\fP"

.PP
Trace log information\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Outpost31 from the source code\&.
