.TH "Outpost31.Module.OpenIncident" 3 "Thu Jun 27 2024" "Outpost31" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Outpost31.Module.OpenIncident
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBModuleOpenIncident\fP"
.br
.ti -1c
.RI "class \fBVerify\fP"
.br
.RI "VerifyAuthor command\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Outpost31 from the source code\&.
