.TH "Outpost31.Core.Avatar.ReturnObject" 3 "Thu Jun 27 2024" "Outpost31" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Outpost31.Core.Avatar.ReturnObject \- Logic specific to the returnOptionObject
.PP
\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBFinalize\fP (\fBTingenSession\fP tnSession, string errorCode, string errorMessage='')"
.br
.RI "Format an \fIOptionObject\fP  to be returned to \fBAvatar\fP\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static string \fBAssemblyName\fP = Assembly\&.GetExecutingAssembly()\&.GetName()\&.Name\fR [get, set]\fP"
.br
.RI "Assembly name for log files\&. "
.in -1c
.SH "Detailed Description"
.PP 
Logic specific to the returnOptionObject
.PP
\&. 


.SH "Member Function Documentation"
.PP 
.SS "static void Outpost31\&.Core\&.Avatar\&.ReturnObject\&.Finalize (\fBTingenSession\fP tnSession, string errorCode, string errorMessage = \fR''\fP)\fR [static]\fP"

.PP
Format an \fIOptionObject\fP  to be returned to \fBAvatar\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fItnSession\fP The Tingen session object\&.
.RE
.PP
.PP
Part of the finalization process is assigning a valid error code to the returnOptionObject: 0 Success - Returns the OptionObject without a message  1 Error - Stops the script from processing and displays an message with an 'OK' button  2 OKCancel - Displays a message with 'OK' and 'Cancel' buttons\&.  3 Info - Displays an informational warning message with an 'OK' button\&.  4 YesNo - Displays a message with 'Yes' and 'No' buttons\&.  5 OpenURL - Opens an URL in a browser  6 OpenForm - Presents an OK/Cancel dialog to open a form (only be used on Form Load and Field events)\&.  
.PP
.IP "\(bu" 2
\fIThe returnOptionObject must be propery formatted when returned to \fBAvatar\fP\fP\&.
.br

.IP "\(bu" 2
More information about OptionObjects \fRhere\fP\&.
.PP
.PP
To return a formatted returnOptionObject:
.br
 
.PP
.nf
Core\&.Avatar\&.FormatReturnObject\&.AsErrorCode(tnSession, errorCode, errorMessage);

.fi
.PP
 
.SH "Property Documentation"
.PP 
.SS "string Outpost31\&.Core\&.Avatar\&.ReturnObject\&.AssemblyName = Assembly\&.GetExecutingAssembly()\&.GetName()\&.Name\fR [static]\fP, \fR [get]\fP, \fR [set]\fP"

.PP
Assembly name for log files\&. 
.IP "\(bu" 2
Define the assembly name here so it can be used to write log files throughout the class\&. 
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Outpost31 from the source code\&.
