.TH "Outpost31.Core.Framework.Refresh" 3 "Thu Jun 27 2024" "Outpost31" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Outpost31.Core.Framework.Refresh \- \fBRefresh\fP the Tingen directory structure\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBRefreshOnDisable\fP (\fBTingenSession\fP tnSession)"
.br
.RI "\fBRefresh\fP the Tingen directory structure when Tingen is disabled\&. "
.ti -1c
.RI "static void \fBRefreshOnUnknown\fP (\fBTingenSession\fP tnSession)"
.br
.RI "\fBRefresh\fP the Tingen directory structure when Tingen is in an unknown state\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBRefresh\fP the Tingen directory structure\&. 
.SH "Member Function Documentation"
.PP 
.SS "static void Outpost31\&.Core\&.Framework\&.Refresh\&.RefreshOnDisable (\fBTingenSession\fP tnSession)\fR [static]\fP"

.PP
\fBRefresh\fP the Tingen directory structure when Tingen is disabled\&. 
.IP "\(bu" 2
If Tingen is disabled, might as well update the service status files\&. 
.PP
.PP
\fBParameters\fP
.RS 4
\fItnSession\fP The Tingen \fBSession\fP object
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Outpost31 from the source code\&.
