.TH "Outpost31.Core.Session.Catalog" 3 "Mon Jul 1 2024" "Outpost31" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Outpost31.Core.Session.Catalog \- Soon\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static string \fBCurrentSettings\fP (\fBTingenSession\fP tnSession)"
.br
.RI "Soon\&. "
.ti -1c
.RI "static string \fBSessionDetails\fP (\fBTingenSession\fP tnSession)"
.br
.RI "Soon\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static string \fBAssemblyName\fP = Assembly\&.GetExecutingAssembly()\&.GetName()\&.Name\fR [get, set]\fP"
.br
.RI "Assembly name for log files\&. "
.in -1c
.SH "Detailed Description"
.PP 
Soon\&. 
.SH "Member Function Documentation"
.PP 
.SS "static string Outpost31\&.Core\&.Session\&.Catalog\&.CurrentSettings (\fBTingenSession\fP tnSession)\fR [static]\fP"

.PP
Soon\&. 
.PP
\fBParameters\fP
.RS 4
\fItnSession\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.SS "static string Outpost31\&.Core\&.Session\&.Catalog\&.SessionDetails (\fBTingenSession\fP tnSession)\fR [static]\fP"

.PP
Soon\&. 
.PP
\fBParameters\fP
.RS 4
\fItnSession\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.SH "Property Documentation"
.PP 
.SS "string Outpost31\&.Core\&.Session\&.Catalog\&.AssemblyName = Assembly\&.GetExecutingAssembly()\&.GetName()\&.Name\fR [static]\fP, \fR [get]\fP, \fR [set]\fP"

.PP
Assembly name for log files\&. 
.IP "\(bu" 2
Define the assembly name here so it can be used to write log files throughout the class\&. 
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Outpost31 from the source code\&.
