.TH "Outpost31.Core.Avatar" 3 "Mon Jul 1 2024" "Outpost31" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Outpost31.Core.Avatar
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAvatarData\fP"
.br
.RI "Avatar-specific data and logic\&. "
.ti -1c
.RI "class \fBReturnObject\fP"
.br
.RI "Logic specific to the returnOptionObject
.PP
\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Outpost31 from the source code\&.
