.TH "Outpost31.Core.Configuration.ConfigSettings" 3 "Thu Jun 27 2024" "Outpost31" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Outpost31.Core.Configuration.ConfigSettings \- Tingen configuration settings\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBConfigSettings\fP \fBBuildDefaultObject\fP ()"
.br
.RI "Build a default Tingen configuration object\&. "
.ti -1c
.RI "static \fBConfigSettings\fP \fBLoad\fP (string configPath, string configFileName)"
.br
.RI "Loads the Tingen configuration file\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBTingenMode\fP\fR [get, set]\fP"
.br
.RI "Determines what Tingen does, if anything\&. "
.ti -1c
.RI "string \fBModOpenIncidentMode\fP\fR [get, set]\fP"
.br
.RI "Determines if the \fBOpen Incident \fBModule\fP\fP is enabled\&. "
.ti -1c
.RI "string \fBNtstWebServices\fP\fR [get, set]\fP"
.br
.RI "Determines if the NTST web services are enabled\&. "
.ti -1c
.RI "int \fBTraceLevel\fP\fR [get, set]\fP"
.br
.RI "The trace logging level\&. "
.ti -1c
.RI "int \fBTraceDelay\fP\fR [get, set]\fP"
.br
.RI "The delay between trace log writes\&. "
.in -1c
.SH "Detailed Description"
.PP 
Tingen configuration settings\&. 

Tingen configuration settings: 
.PD 0
.IP "\(bu" 2
Are specific to Tingen core functionality (other components/modules have their own configurations) 
.IP "\(bu" 2
Do not change between Tingen sessions 
.IP "\(bu" 2
Can be modified by the user to suit their environment 
.PP
.PP
.IP "\(bu" 2
The Tingen configuration file is located in \fI'TingenData\\%SystemCode%\\Config\\Tingen\&.config'\fP\&.
.br

.IP "\(bu" 2
More information about configuring Tingen here\&.
.PP

.SH "Member Function Documentation"
.PP 
.SS "static \fBConfigSettings\fP Outpost31\&.Core\&.Configuration\&.ConfigSettings\&.BuildDefaultObject ()\fR [static]\fP"

.PP
Build a default Tingen configuration object\&. 
.IP "\(bu" 2
These are the default values for the Tingen configuration settings\&.
.br

.IP "\(bu" 2
When a new version of Tingen is released, these need to be verified/updated\&.
.br

.IP "\(bu" 2
More information about configuring Tingen here\&.
.PP
.PP
\fBReturns\fP
.RS 4
An object with default Tingen configuration values\&.
.RE
.PP

.SS "static \fBConfigSettings\fP Outpost31\&.Core\&.Configuration\&.ConfigSettings\&.Load (string configPath, string configFileName)\fR [static]\fP"

.PP
Loads the Tingen configuration file\&. 
.PP
\fBParameters\fP
.RS 4
\fIconfigPath\fP Path to the Tingen configuration file\&.
.RE
.PP
.PP
.IP "\(bu" 2
The configuration file path is created in \fBTingen\&.asmx\&.cs\fP
.br

.IP "\(bu" 2
If the configuration file does not exist, a configuration file with default values will be created\&. 
.PP
.PP
\fBReturns\fP
.RS 4
The Tingen configuration settings\&.
.RE
.PP

.SH "Property Documentation"
.PP 
.SS "string Outpost31\&.Core\&.Configuration\&.ConfigSettings\&.ModOpenIncidentMode\fR [get]\fP, \fR [set]\fP"

.PP
Determines if the \fBOpen Incident \fBModule\fP\fP is enabled\&. Valid Open Incident \fBModule\fP modes: Enabled (default) The Open Incident \fBModule\fP is enabled\&.  Disabled The Open Incident \fBModule\fP is disabled\&., and the sentObject is returned to \fBAvatar\fP unmodified\&.  
.PP
.IP "\(bu" 2
Disabling this module not affect other modules, or Tingen as a whole\&.
.br

.IP "\(bu" 2
More information about Tingen modes here\&.
.PP

.SS "string Outpost31\&.Core\&.Configuration\&.ConfigSettings\&.NtstWebServices\fR [get]\fP, \fR [set]\fP"

.PP
Determines if the NTST web services are enabled\&. 
.IP "\(bu" 2
Currently not used, but will be in the future\&.
.br

.IP "\(bu" 2
This should be set to '<b>disabled</b>' until the NTST web services are implemented\&. 
.PP

.SS "string Outpost31\&.Core\&.Configuration\&.ConfigSettings\&.TingenMode\fR [get]\fP, \fR [set]\fP"

.PP
Determines what Tingen does, if anything\&. Valid Tingen modes: Enabled (default) Tingen is enabled, and will hand work off to the requested \fITingen \fBModule\fP\fP\&.  Disabled Tingen is disabled, and the sentObject is returned to \fBAvatar\fP unmodified\&.  
.PP
.IP "\(bu" 2
There is logic to catch \fI'enable'\fP and \fI'disable'\fP, since I kept making that mistake\&.
.br

.IP "\(bu" 2
More information about Tingen modes here\&.
.PP

.SS "int Outpost31\&.Core\&.Configuration\&.ConfigSettings\&.TraceDelay\fR [get]\fP, \fR [set]\fP"

.PP
The delay between trace log writes\&. 
.IP "\(bu" 2
In some cases, logs may be written too quickly, and cause files to be overwritten\&.
.br

.IP "\(bu" 2
By including a short delay, the logs can be written in a way that prevents this from happening\&. 
.PP
.PP
10 (default) 
.SS "int Outpost31\&.Core\&.Configuration\&.ConfigSettings\&.TraceLevel\fR [get]\fP, \fR [set]\fP"

.PP
The trace logging level\&. 
.IP "\(bu" 2
Trace logs with a level less than or equal to the \fITraceLevel\fP  will be written\&.
.br

.IP "\(bu" 2
Trace logs are written to \fI'%TingenDataRoot%\\%AvatarSystemCode%\\YYMM\\%OptionUserId%\\HHMMSS\\'</i>\&.<br/>
  - More information about trace logs can be found <see href='github\&.com/spectrum-health-systems/Tingen-Documentation/blob/main/Glossary\&.md\&.logging'>here</see>\&.
 </para>
</remarks>
  <example>
   If the TraceLogLevel is set to '\fR2\fP', the following log calls will be executed:<br/>
   <c>LogEvent\&.Trace(1, tnSession\&.TraceLogs, Asm);</c><br/>
   <c>LogEvent\&.Trace(2, tnSession\&.TraceLogs, Asm);</c><br/><br/>
   If the TraceLogLevel is set to '\fR2\fP", the following log calls will \fInot\fP be executed:
.br
 \fRLogEvent\&.Trace(4, tnSession\&.TraceLogs, Asm);\fP
.br
 \fRLogEvent\&.Trace(5, tnSession\&.TraceLogs, Asm);\fP \fP
.PP
.PP
\fI \fP
.PP
\fI 0 (default) \fP
.PP
\fI \fP

.SH "Author"
.PP 
Generated automatically by Doxygen for Outpost31 from the source code\&.
