.TH "Outpost31.Core.Framework.Catalog.SystemCodePaths" 3 "Thu Jun 27 2024" "Outpost31" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Outpost31.Core.Framework.Catalog.SystemCodePaths \- System Code paths for Tingen\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBSystemCodePaths\fP \fBBuildObject\fP (string tnDataRoot, string avSystemCode)"
.br
.RI "Builds the system code paths object\&. "
.ti -1c
.RI "static List< string > \fBRequiredPaths\fP (\fBSystemCodePaths\fP systemCodePaths)"
.br
.RI "Returns a list of required System Code paths\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBRoot\fP\fR [get, set]\fP"
.br
.RI "Root path for System Code data\&. "
.ti -1c
.RI "string \fBConfig\fP\fR [get, set]\fP"
.br
.RI "Path for System Code configuration data\&. "
.ti -1c
.RI "string \fBSessions\fP\fR [get, set]\fP"
.br
.RI "Path for System Code session data\&. "
.ti -1c
.RI "string \fBCurrentSession\fP\fR [get, set]\fP"
.br
.RI "Current session path\&. "
.ti -1c
.RI "string \fBExtensions\fP\fR [get, set]\fP"
.br
.RI "Path for Tingen Extensions\&. "
.ti -1c
.RI "string \fBSecurity\fP\fR [get, set]\fP"
.br
.RI "Path for Tingen security-related data\&. "
.ti -1c
.RI "string \fBTemporary\fP\fR [get, set]\fP"
.br
.RI "Path for temporary data\&. "
.ti -1c
.RI "string \fBMessageRoot\fP\fR [get, set]\fP"
.br
.RI "Root for message data\&. "
.ti -1c
.RI "string \fBAlerts\fP\fR [get, set]\fP"
.br
.RI "Path for alert data\&. "
.ti -1c
.RI "string \fBErrors\fP\fR [get, set]\fP"
.br
.RI "Path for error data\&. "
.ti -1c
.RI "string \fBWarnings\fP\fR [get, set]\fP"
.br
.RI "Path for warning data\&. "
.ti -1c
.RI "string \fBExportRoot\fP\fR [get, set]\fP"
.br
.RI "Root for exported data\&. "
.ti -1c
.RI "string \fBReports\fP\fR [get, set]\fP"
.br
.RI "Path for exported reports\&. "
.ti -1c
.RI "string \fBImportRoot\fP\fR [get, set]\fP"
.br
.RI "Root for imported data\&. "
.ti -1c
.RI "string \fBFromAvatar\fP\fR [get, set]\fP"
.br
.RI "Path for imported data from \fBAvatar\fP\&. "
.ti -1c
.RI "string \fBTemplates\fP\fR [get, set]\fP"
.br
.RI "Path for imported templates\&. "
.ti -1c
.RI "string \fBSupportRoot\fP\fR [get, set]\fP"
.br
.RI "Root for support data\&. "
.ti -1c
.RI "string \fBAdmin\fP\fR [get, set]\fP"
.br
.RI "Path for admin data\&. "
.ti -1c
.RI "string \fBArchive\fP\fR [get, set]\fP"
.br
.RI "Path for archived data\&. "
.ti -1c
.RI "string \fBDebugging\fP\fR [get, set]\fP"
.br
.RI "Path for debugging data\&. "
.ti -1c
.RI "string \fBLogs\fP\fR [get, set]\fP"
.br
.RI "Path for log data\&. "
.in -1c
.SH "Detailed Description"
.PP 
System Code paths for Tingen\&. 


.IP "\(bu" 2
The System Code path is where Tingen stores most of it's important day-to-day data\&.
.IP "\(bu" 2
There is a separate System Code path for each \fBAvatar\fP System Code\&. 
.PP

.SH "Member Function Documentation"
.PP 
.SS "static \fBSystemCodePaths\fP Outpost31\&.Core\&.Framework\&.Catalog\&.SystemCodePaths\&.BuildObject (string tnDataRoot, string avSystemCode)\fR [static]\fP"

.PP
Builds the system code paths object\&. 
.PP
\fBParameters\fP
.RS 4
\fItnDataRoot\fP The Tingen data root\&.
.br
\fIavSystemCode\fP The \fBAvatar\fP System Code\&.
.RE
.PP
\fBReturns\fP
.RS 4
The System Code data paths\&.
.RE
.PP

.SS "static List< string > Outpost31\&.Core\&.Framework\&.Catalog\&.SystemCodePaths\&.RequiredPaths (\fBSystemCodePaths\fP systemCodePaths)\fR [static]\fP"

.PP
Returns a list of required System Code paths\&. 
.PP
\fBParameters\fP
.RS 4
\fIsystemCodePaths\fP The System Code paths\&.
.RE
.PP
\fBReturns\fP
.RS 4
The list of required System Code paths\&.
.RE
.PP

.SH "Property Documentation"
.PP 
.SS "string Outpost31\&.Core\&.Framework\&.Catalog\&.SystemCodePaths\&.Admin\fR [get]\fP, \fR [set]\fP"

.PP
Path for admin data\&. C:\\TingenData%SystemCode%\\Support\\Admin
.SS "string Outpost31\&.Core\&.Framework\&.Catalog\&.SystemCodePaths\&.Alerts\fR [get]\fP, \fR [set]\fP"

.PP
Path for alert data\&. C:\\TingenData%SystemCode%\\Messages\\Alerts
.SS "string Outpost31\&.Core\&.Framework\&.Catalog\&.SystemCodePaths\&.Archive\fR [get]\fP, \fR [set]\fP"

.PP
Path for archived data\&. C:\\TingenData%SystemCode%\\Support\\Archive
.SS "string Outpost31\&.Core\&.Framework\&.Catalog\&.SystemCodePaths\&.Config\fR [get]\fP, \fR [set]\fP"

.PP
Path for System Code configuration data\&. C:\\TingenData%SystemCode%\\Config
.SS "string Outpost31\&.Core\&.Framework\&.Catalog\&.SystemCodePaths\&.CurrentSession\fR [get]\fP, \fR [set]\fP"

.PP
Current session path\&. 
.IP "\(bu" 2
Set at runtime\&. 
.PP

.SS "string Outpost31\&.Core\&.Framework\&.Catalog\&.SystemCodePaths\&.Debugging\fR [get]\fP, \fR [set]\fP"

.PP
Path for debugging data\&. C:\\TingenData%SystemCode%\\Support\\Debugging
.SS "string Outpost31\&.Core\&.Framework\&.Catalog\&.SystemCodePaths\&.Errors\fR [get]\fP, \fR [set]\fP"

.PP
Path for error data\&. C:\\TingenData%SystemCode%\\Messages\\Errors
.SS "string Outpost31\&.Core\&.Framework\&.Catalog\&.SystemCodePaths\&.ExportRoot\fR [get]\fP, \fR [set]\fP"

.PP
Root for exported data\&. C:\\TingenData%SystemCode%\\Exports
.SS "string Outpost31\&.Core\&.Framework\&.Catalog\&.SystemCodePaths\&.Extensions\fR [get]\fP, \fR [set]\fP"

.PP
Path for Tingen Extensions\&. 
.IP "\(bu" 2
Future functionality\&. 
.PP

.SS "string Outpost31\&.Core\&.Framework\&.Catalog\&.SystemCodePaths\&.FromAvatar\fR [get]\fP, \fR [set]\fP"

.PP
Path for imported data from \fBAvatar\fP\&. C:\\TingenData%SystemCode%\\Imports\\FromAvatar
.SS "string Outpost31\&.Core\&.Framework\&.Catalog\&.SystemCodePaths\&.ImportRoot\fR [get]\fP, \fR [set]\fP"

.PP
Root for imported data\&. C:\\TingenData%SystemCode%\\Imports
.SS "string Outpost31\&.Core\&.Framework\&.Catalog\&.SystemCodePaths\&.Logs\fR [get]\fP, \fR [set]\fP"

.PP
Path for log data\&. C:\\TingenData%SystemCode%\\Support\\Logs
.SS "string Outpost31\&.Core\&.Framework\&.Catalog\&.SystemCodePaths\&.MessageRoot\fR [get]\fP, \fR [set]\fP"

.PP
Root for message data\&. C:\\TingenData%SystemCode%\\Messages
.SS "string Outpost31\&.Core\&.Framework\&.Catalog\&.SystemCodePaths\&.Reports\fR [get]\fP, \fR [set]\fP"

.PP
Path for exported reports\&. C:\\TingenData%SystemCode%\\Exports\\Reports
.SS "string Outpost31\&.Core\&.Framework\&.Catalog\&.SystemCodePaths\&.Root\fR [get]\fP, \fR [set]\fP"

.PP
Root path for System Code data\&. C:\\TingenData%SystemCode%
.SS "string Outpost31\&.Core\&.Framework\&.Catalog\&.SystemCodePaths\&.Security\fR [get]\fP, \fR [set]\fP"

.PP
Path for Tingen security-related data\&. 
.IP "\(bu" 2
Future functionality\&. 
.PP

.SS "string Outpost31\&.Core\&.Framework\&.Catalog\&.SystemCodePaths\&.Sessions\fR [get]\fP, \fR [set]\fP"

.PP
Path for System Code session data\&. C:\\TingenData%SystemCode%\\Sessions
.SS "string Outpost31\&.Core\&.Framework\&.Catalog\&.SystemCodePaths\&.SupportRoot\fR [get]\fP, \fR [set]\fP"

.PP
Root for support data\&. C:\\TingenData%SystemCode%\\Support
.SS "string Outpost31\&.Core\&.Framework\&.Catalog\&.SystemCodePaths\&.Templates\fR [get]\fP, \fR [set]\fP"

.PP
Path for imported templates\&. C:\\TingenData%SystemCode%\\Imports\\Templates
.SS "string Outpost31\&.Core\&.Framework\&.Catalog\&.SystemCodePaths\&.Temporary\fR [get]\fP, \fR [set]\fP"

.PP
Path for temporary data\&. 
.IP "\(bu" 2
Temporary files\&. 
.PP

.SS "string Outpost31\&.Core\&.Framework\&.Catalog\&.SystemCodePaths\&.Warnings\fR [get]\fP, \fR [set]\fP"

.PP
Path for warning data\&. C:\\TingenData%SystemCode%\\Messages\\Warnings

.SH "Author"
.PP 
Generated automatically by Doxygen for Outpost31 from the source code\&.
