.TH "C:/Users/cbanw/GitHub/Spectrum Health Systems/Outpost31/src/README.md" 3 "Mon Jul 1 2024" "Outpost31" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/cbanw/GitHub/Spectrum Health Systems/Outpost31/src/README.md
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Outpost31 from the source code\&.
