.TH "C:/Users/cbanw/GitHub/Spectrum Health Systems/Outpost31/src/Module/Admin/Service/Status.cs" 3 "Mon Jul 1 2024" "Outpost31" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/cbanw/GitHub/Spectrum Health Systems/Outpost31/src/Module/Admin/Service/Status.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBOutpost31\&.Module\&.Admin\&.Service\&.Status\fP"
.br
.RI "Soon\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBOutpost31\fP"
.br
.ti -1c
.RI "namespace \fBOutpost31\&.Module\fP"
.br
.ti -1c
.RI "namespace \fBOutpost31\&.Module\&.Admin\fP"
.br
.ti -1c
.RI "namespace \fBOutpost31\&.Module\&.Admin\&.Service\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Outpost31 from the source code\&.
