Outpost31::Core::Logger::LogEvent
static void Outpost31.Core.Logger.LogEvent.Trace(int logLevel, string assemblyName, TraceLog traceInfo, string message="", [CallerFilePath] string fromPath="", [CallerMemberName] string fromMethod="", [CallerLineNumber] int line=0)
Log a trace event.
Trace logs are used to record information about the application's execution. Records information about Tingen's execution Used when debugging/troublshooting during development, and should probably be disabled in production Important details are in the filename: assemblyName%-calledClass%-calledMethod%-lineNumber.trace Do not contain any data To ensure all logs are captured, filenames start with a timestamp: ssfffffff_ Extension is .trace More information about Trace logs here .
References Outpost31.Core.Logger.TraceLog.Create.
Referenced by Outpost31.Module.Common.Action.Field.CompareValue, Outpost31.Core.Session.Catalog.CurrentSettings, Outpost31.Core.Avatar.ReturnObject.Finalize, Outpost31.Module.OpenIncident.Verify.OriginalAuthorIsSubmitting, Outpost31.Core.ParseScriptParameter.Parse, Outpost31.Module.Common.Action.Field.SaveValue, Outpost31.Core.Session.Catalog.SessionDetails, Outpost31.Core.TingenApp.Start, Outpost31.Core.TingenApp.Stop.
static void Outpost31.Core.Logger.LogEvent.Primeval(string assemblyName, string message="Tingen primeval log", [CallerFilePath] string fromPath="", [CallerMemberName] string fromMethod="", [CallerLineNumber] int line=0)
Log a primeval event.
Primeval logs are vary simple logs that can be created with very little information. Do not require any paramaters Used when debugging/troublshooting during development, and should be disabled in production Important details can be found in the file contents May have custom messages (the default message is "Tingen primeval log" To ensure all logs are captured, filenames are timestamped yyMMddHHmmssfffffff Extenstion is .primeval More information about Primeval logs here .
References Outpost31.Core.Logger.PrimevalLog.Create.