Outpost31::Core::Framework::Maintenance
string Outpost31.Core.Framework.Maintenance.AssemblyName
Assembly name for log files.
Define the assembly name here so it can be used to write log files throughout the class.
static void Outpost31.Core.Framework.Maintenance.CleanSessionData()
Soon.
static void Outpost31.Core.Framework.Maintenance.VerifyFramework(TingenSession tnSession)
Verify the Tingen framework.
tnSession The Tingen Session object.
References Outpost31.Core.Session.TingenSession.TnPath, Outpost31.Core.Framework.Maintenance.VerifyDirectories.
Referenced by Outpost31.Core.Framework.Refresh.RefreshOnDisable, Outpost31.Core.Framework.Refresh.RefreshOnUnknown.
static void Outpost31.Core.Framework.Maintenance.RefreshDirectory(string directoryPath)
Delete a directory, then recreate it.
directoryPath The path to the directory to refresh.
static void Outpost31.Core.Framework.Maintenance.VerifyDirectory(string directoryPath)
Verify a directory exists, and create it if it does not.
directoryPath The path to the directory to verify.
Referenced by Outpost31.Core.Session.TingenSession.Initialize.
static void Outpost31.Core.Framework.Maintenance.VerifyDirectories(List< string > directoryPaths)
Verify a list of directories exist, and create them if they do not.
directoryPaths The list of directories to verify.
Referenced by Outpost31.Core.Framework.Maintenance.VerifyFramework.
static void Outpost31.Core.Framework.Maintenance.TESTER()
Tester.