Outpost31::Core::Session::TingenSession
string Outpost31.Core.Session.TingenSession.TnVersion
Referenced by Outpost31.Core.Session.TingenSession.Build.
string Outpost31.Core.Session.TingenSession.TnBuild
Referenced by Outpost31.Core.Session.TingenSession.Build.
string Outpost31.Core.Session.TingenSession.Date
The session datestamp.
Referenced by Outpost31.Core.Session.TingenSession.Build.
string Outpost31.Core.Session.TingenSession.Time
The session timestamp.
Referenced by Outpost31.Core.Session.TingenSession.Build, Outpost31.Core.Session.Catalog.SessionDetails.
bool Outpost31.Core.Session.TingenSession.ReturnClonedOptionObject
Return the cloned OptionObject.
Referenced by Outpost31.Core.Session.TingenSession.Build.
ConfigSettings Outpost31.Core.Session.TingenSession.TnConfig
Config.
Referenced by Outpost31.Core.Session.TingenSession.Build, Outpost31.Core.ParseScriptParameter.Parse, Outpost31.Core.ParseScriptParameter.ParseAdminModule, Outpost31.Core.TingenApp.Start, Outpost31.Module.Admin.Service.Status.UpdateAll.
Paths Outpost31.Core.Session.TingenSession.TnPath
Tingen Framework information.
See Outpost31.Core.Configuration.TingenFramework.cs for more information.
Referenced by Outpost31.Core.Session.TingenSession.Build, Outpost31.Module.OpenIncident.ModuleOpenIncident.GetAuthorInformation, Outpost31.Core.Session.TingenSession.Initialize, Outpost31.Core.ParseScriptParameter.ParseAdminModule, Outpost31.Module.Admin.Service.Status.UpdateAll, Outpost31.Module.Admin.Service.Status.UpdateSettings, Outpost31.Core.Framework.Maintenance.VerifyFramework.
AvatarData Outpost31.Core.Session.TingenSession.AvData
Avatar components .
See Outpost31.Core.Configuration.TingenFramework.cs for more information.
Referenced by Outpost31.Core.Session.TingenSession.Build, Outpost31.Core.Avatar.ReturnObject.Finalize, Outpost31.Module.OpenIncident.ModuleOpenIncident.GetAuthorInformation, Outpost31.Core.ParseScriptParameter.Parse, Outpost31.Core.ParseScriptParameter.ParseAdminModule, Outpost31.Core.ParseScriptParameter.ParseOpenIncidentModule, Outpost31.Core.ParseScriptParameter.ParseTestingModule, Outpost31.Module.Admin.Service.Status.UpdateAll.
NtstWebServiceSecurity Outpost31.Core.Session.TingenSession.NtstWebServiceSecurity
Referenced by Outpost31.Core.Session.TingenSession.Build.
TraceLog Outpost31.Core.Session.TingenSession.TraceInfo
Trace log information.
Referenced by Outpost31.Core.Session.Catalog.CurrentSettings, Outpost31.Core.Avatar.ReturnObject.Finalize, Outpost31.Module.OpenIncident.ModuleOpenIncident.GetAuthorInformation, Outpost31.Module.OpenIncident.Verify.OriginalAuthorIsOpening, Outpost31.Module.OpenIncident.Verify.OriginalAuthorIsSubmitting, Outpost31.Core.ParseScriptParameter.Parse, Outpost31.Core.ParseScriptParameter.ParseAdminModule, Outpost31.Core.ParseScriptParameter.ParseOpenIncidentModule, Outpost31.Core.ParseScriptParameter.ParseTestingModule, Outpost31.Core.Session.Catalog.SessionDetails, Outpost31.Core.TingenApp.Start, Outpost31.Core.TingenApp.Stop, Outpost31.Module.Admin.Service.Status.UpdateAll, Outpost31.Module.Admin.Service.Status.UpdateSettings.
ModuleOpenIncident Outpost31.Core.Session.TingenSession.ModOpenIncident
Module to open an incident.
Referenced by Outpost31.Module.OpenIncident.Verify.OriginalAuthorIsOpening, Outpost31.Module.OpenIncident.Verify.OriginalAuthorIsSubmitting, Outpost31.Core.ParseScriptParameter.Parse.
static TingenSession Outpost31.Core.Session.TingenSession.Build(OptionObject2015 sentOptionObject, string sentScriptParameter, string tnVersion)
Builds the Tingen Session object.
configFile The path to the Tingen configuration file. sentOptionObject The OptionObject sent from Avatar. sentScriptParameter The ScriptParameter sent from Avatar. The Tingen Session contains all of the information that Tingen needs to do what it does, including: Configuration settings (user-definable settings from the configFile ) Static settings (these do not change between sessions) Runtime settings (unique to the current session) Data sent from Avatar, including the sentOptionObject and sentScriptParameter Data derived from the sentOptionObject or sentScriptParameter . Required Tingen Module details. More information about this method: This method is one of the most important in Tingen, as it builds the Tingen Session object. The Session object is built in this order: A basic TingenSession object is initalized with the current date, time, configuration settings, and Avatar data. Framework information is added seperately. Trace log information is added seperately. Module objects are added seperately. An Tingen Session object.
References Outpost31.Core.Session.TingenSession.AvData, Outpost31.Core.Framework.Paths.Build, Outpost31.Core.Logger.TraceLog.BuildInfo, Outpost31.Core.Avatar.AvatarData.BuildObject, Outpost31.Core.Session.TingenSession.BuildStaticVars, Outpost31.Core.Session.TingenSession.Date, Outpost31.Core.Session.TingenSession.Initialize, Outpost31.Core.Configuration.ConfigSettings.Load, Outpost31.Core.NtstWebService.NtstWebServiceSecurity.Load, Outpost31.Module.OpenIncident.ModuleOpenIncident.Load, Outpost31.Core.Session.TingenSession.NtstWebServiceSecurity, Outpost31.Core.Session.TingenSession.ReturnClonedOptionObject, Outpost31.Core.Session.TingenSession.Time, Outpost31.Core.Session.TingenSession.TnBuild, Outpost31.Core.Session.TingenSession.TnConfig, Outpost31.Core.Session.TingenSession.TnPath, Outpost31.Core.Session.TingenSession.TnVersion.
static void Outpost31.Core.Session.TingenSession.Initialize(TingenSession tnSession)
Soon.
tnSession
References Outpost31.Core.Framework.Paths.Remote, Outpost31.Core.Framework.Paths.SystemCode, Outpost31.Core.Session.TingenSession.TnPath, Outpost31.Core.Framework.Maintenance.VerifyDirectory.
Referenced by Outpost31.Core.Session.TingenSession.Build.
static void Outpost31.Core.Session.TingenSession.WriteSessionDetails(TingenSession tnSession)
References Outpost31.Core.Session.Catalog.SessionDetails.
Referenced by Outpost31.Core.TingenApp.Stop.
static Dictionary< string, string > Outpost31.Core.Session.TingenSession.BuildStaticVars()
Referenced by Outpost31.Core.Session.TingenSession.Build.